Repository saranicoly/viagem-no-tempo, pull requests merged in 2022-10, with the labels that each got.

#3 Atualização no script de povoamento
  Projeto Físico/povoamento auxiliar.sql
Labels: enhancement

#6 Population
  Projeto Físico/povoamento auxiliar.sql
Labels: enhancement

#1 Adiciona consulta por group_by / having
  Projeto Físico/consultas.sql
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#2 Add consultas outer join
  Projeto Físico/outerjoin.sql
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#4 Criação de uma consulta utilizando a cláusula 'inner join'
  Projeto Físico/Consultas SQL/inner join.sql
Labels: enhancement

#10 Atualizações na descrição do projeto
  Projeto Conceitual/minimundo.pdf
  README.md
Labels: documentation
